### ISSUE TITLE
[1pt] Old icon in the authentication input form

### ISSUE THREAD

**Issue by ArtDu** [tarantool/front-ui-kit#271]
Please check if the icon is old there. There is such a problem on `TDG_VERSION = 2.3.0-0-g971593f3b`.

![image](https://user-images.githubusercontent.com/22258443/141815483-fb6d5943-8835-4e59-b955-ade61ff054e6.png)

**Comment by usenko-timur** [comment]
@OlgaYakovleva 
Already fixed in the master branch (cartridge). It needs to be checked.

**Comment by OlgaYakovleva** [comment]
Now this form looks this way
![image](https://user-images.githubusercontent.com/86589970/147686329-7be5a4ae-ab50-4f37-94e5-92c1ad4987c1.png)
It seems correctly
